### ISSUE TITLE
mixamo_to_openpose.bat  not working 

### ISSUE THREAD

**Issue by Niutonian** [Astropulse/mixamotoopenpose#1]
Hello, I've been trying to run your script, but sadly I get this error when dragging a .DAE file into mixamo_to_openpose.bat,
here is the error msg:

```
Starting conversion process...
Converting E:\MIXAMOOPENPOSE\mixamotoopenpose\EasyMode\Strut_Walking.dae to OpenPose
Traceback (most recent call last):
  File "E:\MIXAMOOPENPOSE\mixamotoopenpose\EasyMode\utils\mixamo_to_openpose.py", line 401, in <module>
    convert_dae(args["input"], args["output"], image_size=(args["width"], args["height"]), rotation_angles=(args["rotation_x"], args["rotation_y"], args["rotation_z"]), scale_factor=args["scale"], input_fps=args["input_fps"], max_frames=args["max_frames"], output_format=args["output_format"])
  File "E:\MIXAMOOPENPOSE\mixamotoopenpose\EasyMode\utils\mixamo_to_openpose.py", line 342, in convert_dae
    frames = load_keypoints_for_drawing(convert_dae_to_openpose(dae_file, image_size=image_size, rotation_angles=rotation_angles, scale_factor=scale_factor))
  File "E:\MIXAMOOPENPOSE\mixamotoopenpose\EasyMode\utils\mixamo_to_openpose.py", line 251, in convert_dae_to_openpose
    frames = parse_dae_for_visual_scene(dae_file, image_size=image_size, rotation_angles=rotation_angles, scale_factor=scale_factor)
  File "E:\MIXAMOOPENPOSE\mixamotoopenpose\EasyMode\utils\mixamo_to_openpose.py", line 124, in parse_dae_for_visual_scene
    parse_joint(root_node, np.eye(4), time_idx)
  File "E:\MIXAMOOPENPOSE\mixamotoopenpose\EasyMode\utils\mixamo_to_openpose.py", line 97, in parse_joint
    joint_name = node.get('id')
AttributeError: 'NoneType' object has no attribute 'get'
Conversion complete. Output saved to output\Strut_Walking.GIF
Press any key to continue . . .
```

Thanks in advance for your advice

**Comment by Astropulse** [comment]
This looks like an issue with the .dae file not having some of the expected nodes, specifically the "mixamorig_Hips" node.

Can you send the .dae file you were using?

**Comment by Niutonian** [comment]
Hello, here is the file:
https://we.tl/t-RRUmqVju3a

**Comment by Astropulse** [comment]
Yeah this does not follow the expected format- I assume thats because it has texture elements as well as the rig itself. I'll make the conditions for accepting rig names less strict.

**Comment by Astropulse** [comment]
This DAE file is unusable, as it doesn't contain keyframe data for the expected points. Download a properly formatted DAE file.

**Comment by Niutonian** [comment]
Hey thanks for your quick reply, could you let me know a good method to download DAE's from Mixamo

here are my settings 
![Screenshot 2024-11-10 155953](https://github.com/user-attachments/assets/e25a98e4-a141-44c1-99af-309dd99843a9)


How do I export the correct keyframe data?

**Comment by Astropulse** [comment]
Use the X BOT or other simple geometry models and export as collada without skin. 
![image](https://github.com/user-attachments/assets/bfe81a94-d244-4636-95bc-4c52426e0352)
